### ISSUE TITLE
EcalDataProcessor does not process EcalHits correctly.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hpstr#105]
This needs further testing first, however, we observed that for a finalstateparticle that is assigned a photon (pdg = 22), the CalCluster did not have a seed hit or any other hits when using getSeed() or using getHits()

We need to consistently associate the correct hits with an EcalCluster.

**Comment by cbravo135** [comment]
Are we sure this is a hpstr issue and not a hps-java issue?

**Comment by mholtrop** [comment]
Issue is with the recoTuple_cfg.py which commented out the EcalHits. Fix is easy and is in pull request.
