### ISSUE TITLE
Extend ParameterSet

### ISSUE THREAD

**Issue by cbravo135** [JeffersonLab/hpstr#27]
We should discuss and implement support for more data types in Parameter set. First request would be to include Bool and VBool. We should discuss more about what may be needed in the future to be passed to processors from config.py.

**Comment by pbutti** [comment]
Status of this?

**Comment by omar-moreno** [comment]
We have moved away from using ParameterSet in ldmx in favor of std::map <
std::string, std::any >. This is a much cleaner solution and will work with
all types.  I can copy over what I have done if it's useful. 

The only problem I see is that we may need to use a newer standard or
boost.  This is something that should be done at some point anyway.

**Comment by omar-moreno** [comment]
@pbutti Should we close this issue? I don't think it's needed.

**Comment by pbutti** [comment]
Closed
