### ISSUE TITLE
Python files do not follow standard layout

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hpstr#62]
Some of the hpstr Python directories are not structured correctly.

The `pyplot` directory should really be in a dir like `python/hpstr/pyplot` to avoid possible namespace clashes with the well-known pyplot module of Matplotlib. This will also allow it to be used as a proper package rather than just a collection of modules (Python files).

To use modules in pyplot currently requires adding the `pyplot` dir directory to the `PYTHONPATH`. Instead, it would be preferable if only the installed `lib/python` dir was in the `PYTHONPATH`, and then all directories underneath it would be properly accessible as packages. Doing it this way would also allow using the `__init__.py` files in the proper way (whereas currently this would not work as pyplot is not actually a properly structured Python package).

These issues could be fixed by creating a `python` dir and putting all pure Python packages underneath it, rather than having them in the top level project.

These comments do not apply to the Python cfg files, as these are not imported but executed from the command line.

**Comment by pbutti** [comment]
Hi Jeremy, 
Thank you for working on this:
1) Feel free to change name to the folder so doesn't clashes with well know packages
2) Feel free to re-organize the internal structure and add the __init__.py. Also, the plotting scripts are quite basic and we don't need very complicated routines to make comparison plots. It's basically a place where to hold plotting stile and simple plotting scripts =)
Cheers,
PF
