### ISSUE TITLE
Add class and processor for hodoscope output.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hpstr#9]
Add a class to event to contain the hodoscope information and a processor to fill it. 

Relevant information from LCIO: HodoCalHits, HodoGenericClusters, HodoGenericHits, HodoReadoutHits

**Comment by pbutti** [comment]
Hi guys! 
What's the status of this issue? 
I agree is lower priority wrt other stuff. Just to keep track of how things are going

Cheers,
PF

**Comment by pbutti** [comment]
Status?

**Comment by omar-moreno** [comment]
@pbutti I'm wondering how you think we should approach this.  Do you think we should have a processor that creates a flat ntuple or persist to an object?

**Comment by mholtrop** [comment]
@omar-moreno I had started to work on this, then got waylaid with other things. 
I would put the hodoscope hits into an object very nearly identical to an Ecal hit. So, yes, processor and object would be my choice.
What slowed me down was that the current hps-java code writes all the information twice, so I needed to first decide which way hps-java should write the LCIO file, so that then hpstr reads the correct information.

**Comment by pbutti** [comment]
Hi @maurik @omar-moreno ,

a processor for converting the hodoscope hit from LCIO to ROOT, a new class representing the Hodoscope Hit, then probably we need links between particles to hodo hits too?

**Comment by mholtrop** [comment]
Hi @pbutti,

I have the classes for hodoscope hits and clusters implemented on "iss9", and also the reader, which is now working. 
It would be nice to have the links between MCParticles (I assume that you mean truth matching in your statement) and hodohits, however the current hps-java driver does NOT store those, so it would need to be added to hps-java first. 
I think we can add that to hpstr in a subsequent issue, once it exists in the LCIO file.

**Comment by pbutti** [comment]
Hi @mholtrop ,

Yes I see the reader/clusters/hit request =) I'm happy to merge it in.
I wasn't asking about truth matching, which is useful too tho, but also the FinalStateParticle <-> HodoCluster relation. Does that exist already?

**Comment by mholtrop** [comment]
Hi @pbutti PF,
I agree, we need to get FinalStateParticle and/or track and MCParticle relations added in, but I think those first need to be added to the hps-java side. I don't think those are there yet. I will check with Rafo, and make an issue for hps-java. Thanks for the reminder.
