### ISSUE TITLE
Fix cmake scheme for v6.20.x version of root.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hpstr#95]
Currently the cmake scheme we use will compile the dictionary file created by rootcling twice, once right after the dictionary is created and again later after all the standard code is compiled. Both resulting object files are then linked, causing a linker error.
It is not yet clear where exactly this goes wrong.  This only affects root v6.20.x so it is a minor issue.

**Comment by mholtrop** [comment]
For the "event" directory, if I comment out the line "EXTRA_SOURCES EventDict.cxx", the code compiles fine.

**Comment by mholtrop** [comment]
Here is the change in behavior from the ROOT 6.20 release notes (https://root.cern/doc/v620/release-notes.html):

> The macro ROOT_GENERATE_DICTIONARY() can now attach the generated source file directly to a library target by using the option MODULE <library>, where <library> is an existing library target. This allows the dictionary to inherit target properties such as compile options and include directories from the library target, even when they are added after the call to ROOT_GENERATE_DICTIONARY().

It seems that removing "MODULE ${PROJECT_NAME}" is a better way to solve this. Just need to make sure it also fixes the problem in Linux versions.

**Comment by pbutti** [comment]
This fixed? Seems like it's in master

**Comment by omar-moreno** [comment]
Yes.

**Comment by omar-moreno** [comment]
Resolved by #96
